# Generated by Django 5.1.3 on 2024-12-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "soft_delete",
                ),
                "permissions": [("change_post_status", "Can change post status")],
            },
        ),
    ]
